/**
 * This device is a cunt and so is the documentation. Here's some keywords used in the docs
 * that won't make sense unless you sift through it:
 * 
 * PPI: Private Peripheral Interrupt (PPI)
 *      This is a peripheral interrupt that is specific to a single processor.
 *
 * SPI: Shared Peripheral Interrupt (SPI)
 *      This is a peripheral interrupt that the Distributor can route to any of a specified
 *      combination of processors
 *
 * SGI: Software Generated interrupt
 *      This is an interrupt generated by software writing to a GICD_SGIR register in the GIC. The
 *       system uses SGIs for interprocessor communication.
 *
 */
#pragma once

#include <stdint.h>

static constexpr uintptr_t GIC_BASE = 0x2c000000;
static constexpr uintptr_t GIC_DIST_BASE = 0x2c001000;
static constexpr uintptr_t GIC_CPU_BASE = 0x2c002000;
static constexpr uint16_t GIC_SIZE = 0x8000; // 32KiB of space
static constexpr uint16_t GIC_CPU_INTERFACE_OFFSET = 0x2000;

namespace GIC
{
void initialize();
void enable_interrupt(uint8_t irq);
void disable_interrupt(uint8_t irq);
void eoi(uint16_t irq);

uint16_t interrupt_id();

}; // namespace GIC