/**
 * This device is a cunt and so is the documentation. Here's some keywords used in the docs
 * that won't make sense unless you sift through it:
 * 
 * PPI: Private Peripheral Interrupt (PPI)
 *      This is a peripheral interrupt that is specific to a single processor.
 *
 * SPI: Shared Peripheral Interrupt (SPI)
 *      This is a peripheral interrupt that the Distributor can route to any of a specified
 *      combination of processors
 *
 * SGI: Software Generated interrupt
 *      This is an interrupt generated by software writing to a GICD_SGIR register in the GIC. The
 *       system uses SGIs for interprocessor communication.
 *
 */
#pragma once

#include <stdint.h>

namespace GIC
{
void initialize();
void enable_interrupt(uint8_t irq);
void disable_interrupt(uint8_t irq);
void eoi(uint16_t irq);

uint16_t interrupt_id();

}; // namespace GIC